### ISSUE TITLE
make footnotes work

### ISSUE THREAD

**Issue by swyxio** [swyxio/swyxkit#129]
currently they dont work

https://github.com/orgs/remarkjs/discussions/1024#discussioncomment-3345267

gives some indicationt hat it should work if we bump the deps

**Comment by Bishwas-py** [comment]
@swyxio Doing it.

**Comment by swyxio** [comment]
would honestly still prefer it to be supported as a remark plugin, but cheers to @Bishwas-py for supporting it!
